In [3]:
import pandas as pd
import numpy as np

reports=pd.read_csv("./indiana_reports.csv")
projections=pd.read_csv("./indiana_projections.csv")
reports.head()

,uid,MeSH,Problems,image,indication,comparison,findings,impression
0,1,normal,normal,Xray Chest PA and Lateral,Positive TB test,None.,The cardiac silhouette and mediastinum size ar...,Normal chest x-XXXX.
1,2,Cardiomegaly/borderline;Pulmonary Artery/enlarged,Cardiomegaly;Pulmonary Artery,"Chest, 2 views, frontal and lateral",Preop bariatric surgery.,None.,Borderline cardiomegaly. Midline sternotomy XX...,No acute pulmonary findings.
2,3,normal,normal,Xray Chest PA and Lateral,"rib pain after a XXXX, XXXX XXXX steps this XX...",NaN,NaN,"No displaced rib fractures, pneumothorax, or p..."
3,4,"Pulmonary Disease, Chronic Obstructive;Bullous...","Pulmonary Disease, Chronic Obstructive;Bullous...","PA and lateral views of the chest XXXX, XXXX a...",XXXX-year-old XXXX with XXXX.,None available,There are diffuse bilateral interstitial and a...,1. Bullous emphysema and interstitial fibrosis...
4,5,Osteophyte/thoracic vertebrae/multiple/small;T...,Osteophyte;Thickening;Lung,Xray Chest PA and Lateral,Chest and nasal congestion.,NaN,The cardiomediastinal silhouette and pulmonary...,No acute cardiopulmonary abnormality.

In [4]:
reports.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3851 entries, 0 to 3850
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   uid         3851 non-null   int64
 1   MeSH        3851 non-null   object
 2   Problems    3851 non-null   object
 3   image       3851 non-null   object
 4   indication  3765 non-null   object
 5   comparison  3252 non-null   object
 6   findings    3337 non-null   object
 7   impression  3820 non-null   object
dtypes: int64(1), object(7)
memory usage: 240.8+ KB

In [5]:
reports["findings"].isna().sum()

514

In [6]:
projections.head()

   uid                filename projection
0    1  1_IM-0001-4001.dcm.png    Frontal
1    1  1_IM-0001-3001.dcm.png    Lateral
2    2  2_IM-0652-1001.dcm.png    Frontal
3    2  2_IM-0652-2001.dcm.png    Lateral
4    3  3_IM-1384-1001.dcm.png    Frontal

In [7]:
vc=projections["uid"].value_counts()
uids_1=[key for key,value in zip(vc.keys(),vc.values) if value==1] #uids using a single image for report
len(uids_1)
# list(vc.values).count(1)

446

In [8]:
clean_reports=reports.dropna(axis=0,subset=['findings'])
clean_reports.shape

(3337, 8)

In [9]:
reports.shape

(3851, 8)

In [10]:
clean_reports

,uid,MeSH,Problems,image,indication,comparison,findings,impression
0,1,normal,normal,Xray Chest PA and Lateral,Positive TB test,None.,The cardiac silhouette and mediastinum size ar...,Normal chest x-XXXX.
1,2,Cardiomegaly/borderline;Pulmonary Artery/enlarged,Cardiomegaly;Pulmonary Artery,"Chest, 2 views, frontal and lateral",Preop bariatric surgery.,None.,Borderline cardiomegaly. Midline sternotomy XX...,No acute pulmonary findings.
3,4,"Pulmonary Disease, Chronic Obstructive;Bullous...","Pulmonary Disease, Chronic Obstructive;Bullous...","PA and lateral views of the chest XXXX, XXXX a...",XXXX-year-old XXXX with XXXX.,None available,There are diffuse bilateral interstitial and a...,1. Bullous emphysema and interstitial fibrosis...
4,5,Osteophyte/thoracic vertebrae/multiple/small;T...,Osteophyte;Thickening;Lung,Xray Chest PA and Lateral,Chest and nasal congestion.,NaN,The cardiomediastinal silhouette and pulmonary...,No acute cardiopulmonary abnormality.
5,6,normal,normal,"PA and Lateral Chest. XXXX, XXXX at XXXX",Evaluate for infection,"XXXX, XXXX",Heart size and mediastinal contour are within ...,No acute cardiopulmonary findings.
...,...,...,...,...,...,...,...,...
3844,3993,Cardiomegaly/mild;Diaphragm/left/elevated,Cardiomegaly;Diaphragm,CHEST 2V FRONTAL/LATERAL,Edema,None,The heart is mildly enlarged. Left hemidiaphra...,Borderline cardiomegaly without acute disease.
3845,3994,Cardiomegaly/mild;Pulmonary Congestion;Heart F...,Cardiomegaly;Pulmonary Congestion;Heart Failure,2 view ( PA and lateral) chest radiograph date...,"XXXX-year-old male with chest pain, positive t...","Portable chest x-XXXX XXXX, XXXX",Similar mild cardiomegaly. Of the pulmonary va...,Mild cardiomegaly with XXXX of early failure.
3846,3995,Lung/hyperdistention/mild;Diaphragm/bilateral/...,Lung;Diaphragm;Cicatrix;Pulmonary Atelectasis;...,Xray Chest PA and Lateral,"Nausea, vomiting x2 weeks. Dialysis patient.","XXXX, XXXX.",The cardiomediastinal silhouette and pulmonary...,1. Interval resolution of bibasilar airspace d...
3847,3996,Spine/degenerative,Spine,Xray Chest PA and Lateral,NaN,None.,The lungs are clear. Heart size is normal. No ...,Clear lungs. No acute cardiopulmonary abnormal...
3848,3997,Opacity/lung/upper lobe/right/round/small;Gran...,Opacity;Granuloma,PA and lateral views of the chest.,XXXX-year-old male with positive PPD.,None available.,"Heart size within normal limits. Small, nodula...","No acute findings, no evidence for active TB."

In [11]:
clean_uids=list(clean_reports['uid'])
set1=set(uids_1)
set2=set(clean_uids)
uids=list(set2.intersection(set1))
len(uids)

382

In [12]:
clean_reports.to_csv("./clean_indiana_reports.csv")

In [13]:
df_new=pd.merge(clean_reports,projections, on='uid')
df_new.head()

,uid,MeSH,Problems,image,indication,comparison,findings,impression,filename,projection
0,1,normal,normal,Xray Chest PA and Lateral,Positive TB test,None.,The cardiac silhouette and mediastinum size ar...,Normal chest x-XXXX.,1_IM-0001-4001.dcm.png,Frontal
1,1,normal,normal,Xray Chest PA and Lateral,Positive TB test,None.,The cardiac silhouette and mediastinum size ar...,Normal chest x-XXXX.,1_IM-0001-3001.dcm.png,Lateral
2,2,Cardiomegaly/borderline;Pulmonary Artery/enlarged,Cardiomegaly;Pulmonary Artery,"Chest, 2 views, frontal and lateral",Preop bariatric surgery.,None.,Borderline cardiomegaly. Midline sternotomy XX...,No acute pulmonary findings.,2_IM-0652-1001.dcm.png,Frontal
3,2,Cardiomegaly/borderline;Pulmonary Artery/enlarged,Cardiomegaly;Pulmonary Artery,"Chest, 2 views, frontal and lateral",Preop bariatric surgery.,None.,Borderline cardiomegaly. Midline sternotomy XX...,No acute pulmonary findings.,2_IM-0652-2001.dcm.png,Lateral
4,4,"Pulmonary Disease, Chronic Obstructive;Bullous...","Pulmonary Disease, Chronic Obstructive;Bullous...","PA and lateral views of the chest XXXX, XXXX a...",XXXX-year-old XXXX with XXXX.,None available,There are diffuse bilateral interstitial and a...,1. Bullous emphysema and interstitial fibrosis...,4_IM-2050-1001.dcm.png,Frontal

In [14]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6469 entries, 0 to 6468
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   uid         6469 non-null   int64
 1   MeSH        6469 non-null   object
 2   Problems    6469 non-null   object
 3   image       6469 non-null   object
 4   indication  6366 non-null   object
 5   comparison  5780 non-null   object
 6   findings    6469 non-null   object
 7   impression  6457 non-null   object
 8   filename    6469 non-null   object
 9   projection  6469 non-null   object
dtypes: int64(1), object(9)
memory usage: 555.9+ KB

In [15]:
df_new.shape

(6469, 10)

In [16]:
df_new['findings'].isna().sum()

0

In [17]:
df_new['findings'][0]

'The cardiac silhouette and mediastinum size are within normal limits. There is no pulmonary edema. There is no focal consolidation. There are no XXXX of a pleural effusion. There is no evidence of pneumothorax.'

In [18]:
import os
# Define a function to check if a filepath exists
def check_filepath(filepath):
    return os.path.exists(filepath)
mask = ("./images/images_normalized/"+projections['filename']).apply(check_filepath)
projections_new=projections[mask]
projections_new.shape

(7466, 3)

In [19]:
projections.shape

(7466, 3)

In [22]:
os.path.exists('./images/images_normalized/2276_IM-0863-1001-0002.dcm.png')

True

In [37]:
from PIL import Image
img=Image.open('./images/images_normalized/2276_IM-0863-1001-0002.png')
# ./images/images_normalized/2276_IM-0863-1001-0002.png

UnidentifiedImageError: cannot identify image file './images/images_normalized/2276_IM-0863-1001-0002.png'

In [45]:
# directory='./images/images_normalized'
# files=os.listdir(directory)
count=0
for filename in projections['filename']:
    # if ".dcm" in filename:
    #     # Construct the new file name by removing the ".dcm" part
    #     new_filename = filename.replace(".dcm", "")
    #     # Construct the full paths for the old and new files
    #     old_path = os.path.join(directory, filename)
    #     new_path = os.path.join(directory, new_filename)
    #     # Rename the file
    #     try:
    #         os.rename(old_path, new_path)
    #         print(f"Renamed '{filename}' to '{new_filename}'")
    #     except Exception as e:
    #         print(f"Error renaming '{filename}': {e}")
    try:
        new_name=filename.replace('.dcm','')
        img=Image.open('./images/images_normalized/'+new_name)
        count+=1
    except:
        continue
print(count)
    
projections['filename'].shape

7465

(7466,)

In [35]:
for i, row in projections.iterrows():
    if(".dcm" in row['filename']):
        new_string=row['filename'].replace(".dcm","")
    else:
        new_string=row['filename']
    print(new_string)
    print(os.path.exists('./images/images_normalized/'+new_string))
    img=Image.open('./images/images_normalized/'+new_string)
    img.show()
    break

1_IM-0001-4001.png
True